Lambda-School-Labs/key-conservation-be

- Models/consModel.js
- Routes/consRouter.js
- api/server.js
- package.json
> added models and routes

- Models/campModel.js
- Routes/campRouter.js
- Routes/consRouter.js
- database/migrations/20190225134140_users.js
- database/migrations/20190715143159_conservationists.js
- database/migrations/20190715143714_campaigns.js
- database/seeds/001-users.js
- database/seeds/002-conservations.js
- database/seeds/003-campaigns.js
> added camp by userID route, seeds, fixed db

- campaigns/campModel.js
> deleted a semicolon

- campaigns/campModel.js
> Added an 's'

- database/migrations/20190225134140_users.js
- database/seeds/001-users.js
- users/usersModel.js
- users/usersRouter.js
Small tweaks to help integrate Auth0.
> added sub column to database, made tweaks to help user creation

- users/usersModel.js
> more bugfixin

- users/usersModel.js
> added campaign data to find user by id / sub

- database/migrations/20190715143159_conservationists.js
- users/usersModel.js
- added org_cta column to conservationists table
- changed name of "org_link_title" to "org_link_text"
- fixed update user endpoint
> added org_cta column to conservationists table

- database/migrations/20190225134140_users.js
- knexfile.js
- package-lock.json
Want to make the sub field unique so it won't have users with the same id making multiple accounts.
- [x ] I have performed a self-review of my own code
> Making the sub field unique

- database/seeds/003-campaigns.js
added new campaign description lorem ipsum
> added new campaign description lorem ipsum

- package-lock.json
- users/usersModel.js
bring development changes into master
> Merging Development

- database/seeds/003-campaigns.js
> seeds for 1st rollout, corrected

- campaigns/campModel.js
tweaked campaign deletion to return id of deleted campaign
> tweaked campaign deletion to return id of deleted campaign

- database/migrations/20190225134140_users.js
- database/migrations/20190715143159_conservationists.js
- database/migrations/20190809133327_supporters.js
- database/seeds/001-users.js
- database/seeds/002-conservations.js
- users/usersModel.js
created supporters table, modified existing migrations, seeds, and models to support changes
> supporters table

- users/usersModel.js
- users/usersRouter.js
fixing a tiny little problem that may have broken the backend.
> small bugfix

- users/usersModel.js
> changed a semicolon to a comma

- api/server.js
- campaigns/campRouter.js
- knexfile.js
- package-lock.json
- package.json
- upload/s3-uploads-router.js
>
>
> Co-authored-by: Sam <samjeffcoat@gmail.com>
> Adding image-upload

- api/server.js
- campaigns/campRouter.js
- middleware/s3Upload.js
- users/usersRouter.js
Refactoring image S3 upload to middleware functions that can be used throughout the code. 
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
> S3 Refactor

- campaigns/campRouter.js
- middleware/s3Upload.js
- users/usersRouter.js
Small bugfix for "put" routes that use picture upload
> bug fix for put routes

- api/server.js
- campaigns/campRouter.js
- knexfile.js
- middleware/s3Upload.js
- package-lock.json
- package.json
- upload/s3-uploads-router.js
- users/usersRouter.js
> Merging Development to Master

- api/server.js
- campaignUpdates/updateModel.js
- campaignUpdates/updateRouter.js
- database/migrations/20190820141945_campaignUpdates.js
- database/migrations/20190821095102_addUsersIDtoCampaignUpdates.js
- knexfile.js
- users/usersModel.js
- users/usersRouter.js
Co-Authored-By: Pearl Paris <coriagogo@users.noreply.github.com>
Created campaign updates migration table, router, and model. Campaign update contains a primary key, an image, and a description, and uses camp_id as a foreign key. Endpoints include:
GET /updates/ (find all)
GET /updates/:id (find update by update id)
GET /updates/camp/:id (find updates by campaign id)
POST /updates/ (add update)
PUT /updates/:id (edit update)
DELETE /updates/:id (delete update)
> Added campaign updates

- users/usersModel.js
added functionality back in, hopefully without breaking everything.
> Add campaign updates table

- campaignUpdates/updateModel.js
This should fix the updates endpoints
> This should fix everything

- campaigns/campModel.js
- campaigns/campRouter.js
Added updates as an array inside of campaigns for certain endpoints
Co-Authored-By: Pearl Paris <coriagogo@users.noreply.github.com>
> Nesting updates inside campaigns

- users/usersModel.js
> Tiny bugfix

- README.md
- database/migrations/20190918051256_comments.js
- knexfile.js
Added initial comment schema and added it to the README. 
- [✔️  ] I have made corresponding changes to the documentation
> Comments migration

- api/server.js
- auth/restricted.js
- campaigns/campModel.js
- campaigns/campRouter.js
- comments/commentsModel.js
- comments/commentsRouter.js
- knexfile.js
Added comments router and model. Changed campaignModel find() to also return a comments_length prop with each campaign. 
> Added commentsRouter and commentsModel :sparkles:

- campaigns/campModel.js
- comments/commentsModel.js
- comments/commentsRouter.js
Can get all comments for a specific campaign. 
> Comments router and model

- api/server.js
- campaigns/campModel.js
- comments/commentsModel.js
Changed models to better suit figma design files. Pretty minor. 
- [✔️ ] I have performed a self-review of my own code
> Changes to models to better reflect figma design goals.

- comments/commentsModel.js
Changes to comments model to return just the comments for a campaign. Trying to connect the dots on the front-end. 
- [✔️ ] I have commented my code, particularly in hard-to-understand areas
> Changes to comments model

- comments/commentsModel.js
- comments/commentsRouter.js
> :construction: Changes to delete router and model to return id

- campaigns/campModel.js
Joined users table to comments to access usernames and profile images. 
> Adjusted campModel to support FeedCampaign architecture on front end

- api/server.js
- campaignUpdates/updateModel.js
- campaigns/campModel.js
- database/migrations/20190929203708_likes_table.js
- database/migrations/20190929205007_bookmarks_table.js
- knexfile.js
- social/socialModel.js
- social/socialRouter.js
Added migrations for likes and bookmarks. 
> :sparkles: Likes and bookmarks migrations added

- README.md
Added new migration schema to readme. Also the campaignUpdates schema 'cause the old team FORGOT! 
- [✔️ ] I have commented my code, particularly in hard-to-understand areas
- [ ✔️ ] I have made corresponding changes to the documentation
> Readme schema

- api/server.js
- social/socialModel.js
- social/socialRouter.js
Added delete functionality for likes. 
> Social router and model

- social/socialModel.js
- social/socialRouter.js
Modified delete functionality. 
> :construction: Modified like delete route and model

- social/socialRouter.js
Changed like delete route to reference params instead of body to address front-end bug. 
> Changed like delete route

- social/socialModel.js
- social/socialRouter.js
Needed a route specifically for deleting an update post like instead of a campaign post. 
> :construction: Added route for deleting update like

- social/socialRouter.js
Slight change to endpoint for test. 
> :construction: Modified endpoint for update like delete

- social/socialRouter.js
> :construction: Added missing (

- social/socialRouter.js
> :construction: Added route for getting likes by id

- campaignUpdates/updateModel.js
- campaigns/campModel.js
ProScreen view was busted because the feedCampaign/Update views weren't getting access to likes and comments—I've modified the necessary endpoints to return these. May require further tinkering. 
> :ambulance: Should fix profile view

- social/socialModel.js
- social/socialRouter.js
- users/usersModel.js
Routes and models for bookmarks. CurrentUserProfile is retrieved with bookmarks on login. 
> :sparkles: Bookmark routes and modesl added

- social/socialModel.js
- social/socialRouter.js
Changed likes model and routers to fix liking update posts. 
> :construction: Changed likes model

- social/socialModel.js
> :bug: Spelling error in socialModel

- users/usersModel.js
> updates to findById conservationist get request

- airtable-key-retrieval/airtableRouter.js
> whatever didn't get saved

- api/server.js
> adding authorization

- api/server.js
- maps/mapModel.js
- maps/mapRouter.js
> get request for maps

- .env 2
- database/migrations/20191210134552_coordinate-column.js
> longitude and latitude added to conservationist model

- users/usersModel.js
Hopefully this will allow us to update the longitude and latitude in the database.
> added on to put model

- users/usersModel.js
This should give you longitude and latitude
> added longitude and latitude to getById

- api/reports/index.js
- database/migrations/20200127112424_add_strike_counter.js
This update contains important changes to the way posts are reported and reports are retrieved.
Co-authored-by: baca.zach@icloud.com
Co-authored-by: arizephyr123@gmail.com
Data integrity improved - POST handler ensures data posted to reports is 100% valid
Data response improved - More detail response when getting reports - the correct image and name to display on the frontend
> Vital changes to post reporting

- database/migrations/20200204173738_alter_users_table_gin_index.js
Altered users table to add GIN index for full text search
> Alter users table to add GIN index for full text search

- README.md
- api/campaigns/index.js
- api/comments/index.js
- api/index.js
- api/reports/index.js
- api/updates/index.js
- api/users/index.js
- auth/authRouter.js
- database/migrations/20200205135158_archive_reports.js
- middleware/restrictDeactivated.js
- models/campaignModel.js
- models/commentsModel.js
- models/mapModel.js
- models/reportModel.js
- models/updateModel.js
- models/usersModel.js
- Update documentation to reflect changes to database
- Tweak data responses for report routes to better serve frontend
- Secure routes that were previously unsecured
- Add middleware to all routes to prevent deactivated users from accessing data
- Add endpoints to archive reports
This is the final PQ for this feature, not including possible future bug fixes
Note: Unless the admin-screen frontend branch is merged into development, this will cause an error on the frontend where no user would be able to log in properly. Both branches must be merged together for a functioning app.
> User & Post Reporting

- api/users/index.js
> Remove restricted from connections endpoints for testing

- models/connectionsModel.js
Minor fix to the addConnection function
> Fix addConnection function in connectionsModel.js

- api/users/index.js
Fix for the post connection endpoint
> Changed req.body to req.body.connected_id

- api/users/index.js
- models/connectionsModel.js
> debug addConnection

- api/users/index.js
- models/connectionsModel.js
> Add endpoint to get all connections for given user

- api/users/index.js
> Fix for get user connections endpoint

- api/users/index.js
- middleware/connections.js
> Add middleware to prevent same connection from being made more than once

- middleware/connections.js
> Fixed module.exports error

- __tests__/connections.test.js
- database/seeds/connections_seeds.js
> Add seeds for connections tests

- database/seeds/connections_seeds.js
> Fix seed error

- database/seeds/connections_seeds.js
> Add connection_id to seed

- database/seeds/connections_seeds.js
Reverts Lambda-School-Labs/key-conservation-be#122
> Revert "Add connection_id to seed"

- database/seeds/connections_seeds.js
Reverts Lambda-School-Labs/key-conservation-be#121
> Revert "Fix seed error"

- database/migrations/20200213114440_add_accepted_column_to_connections.js
> Add accepted column to connections table

- models/connectionsModel.js
> Syntax fixes

- api/users/index.js
- models/connectionsModel.js
> Removed middleware for testing

- api/users/index.js
- models/connectionsModel.js
> Add status to router post

- api/users/index.js
- models/connectionsModel.js
> Change array to individual objects in addConnection function

- models/connectionsModel.js
> Change objects to single object

- models/connectionsModel.js
> Change param in addConnection

- models/connectionsModel.js
> Return whole connection when added

- models/connectionsModel.js
> Return conneciton

- models/connectionsModel.js
> Fixed getConnectionById function

- middleware/connections.js
> Fix middleware

- api/users/index.js
> Fixed put request

- api/users/index.js
> Fixed params in put request

- api/users/index.js
> Return new connection status in put request

- api/users/index.js
> Syntax fix in put request

- api/users/index.js
- models/connectionsModel.js
> Added json message to successful deletion

- models/connectionsModel.js
> Made getConnectionByUserId apply to either connector or connected

- api/users/index.js
- middleware/connections.js
- models/connectionsModel.js
> Add middleware to prevent user from connecting to themselves

- models/connectionsModel.js
- models/usersModel.js
Return user name and avatar with GET connection request
- [x ] I have performed a self-review of my own code
> Connection edit

- api/users/index.js
- middleware/connections.js
- models/connectionsModel.js
- models/usersModel.js
getConnectionsByUserId now returns user name and avatar along with the rest of the connection data. Middleware to prevent user from connecting to themselves was also fixed and is now working properly.
[x] I have performed a self-review of my own code
[x] I have commented my code, particularly in hard-to-understand areas
[x] I have made corresponding changes to the documentation
> getConnectionsByUserId fixes

- models/usersModel.js
The insert user function could not take a profile_image, so this merge added profile_image to the usersTabelInsert in that function.
[x] I have performed a self-review of my own code
[x] I have made corresponding changes to the documentation
> Add profile_image variable to add user insert

- middleware/connections.js
- models/usersModel.js
Fixed bug with connections checkUniqueIds middleware
> Connect bugfix

- api/users/index.js
- Server now handles status of connections
- Server now retrieves connector id by utilizing user's token
> Connections improvements

- api/users/index.js
- middleware/connections.js
- models/usersModel.js
Adding a user now populates the conservationists or supporters table with the given data
> Fix add user function

- api/users/index.js
- models/connectionsModel.js
- models/usersModel.js
Fixes an issue trying to insert invalid columns
> Hotfix - Bad code in endpoint

- .circleci/config.yml
- package.json
Uses [ESLint](https://eslint.org/) and [Airbnb's base configuration](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb). Some linter errors have been downgraded to warnings to sift through the noise, but fixing all the errors/warnings should definitely be doable.
> add automated linter

- api/users/index.js
Fixed image upload during org onboarding
> Add multer middleware to postUser

- api/users/index.js
This update includes changes that ensure the database always contains an image, including a placeholder John Doe silhouette
> Blank profile pictures

- database/migrations/20200217144046_add_skills_sensors_cameras.js
- knexfile.js
- models/skillsEnum.js
Add 'SENSORS' and 'CAMERA_TRAPS' to the enum in postgres and the enum in
code.
Also disabled Postgres SSL requirement for local development, SSL
is not usually enabled by default in most editions of Postgres.
> Add Sensors, Camera Traps to available skills

- models/campaignModel.js
> Fix name value overlap

- models/campaignModel.js
> linter fixes

- api/social/index.js
Added a get route to fetch user bookmarks.
- [X ] I have performed a self-review of my own code
> add get route for user bookmarks

- .eslintrc.json
- api/campaigns/index.js
- api/reports/helpers.js
- api/reports/index.js
- api/users/index.js
- database/migrations/.eslintrc.json
- database/seeds/.eslintrc.json
- database/seeds/003-campaigns.js
- index.js
- knexfile.js
- logger/index.js
- middleware/restrictDeactivated.js
- middleware/s3Upload.js
- models/applicationSubmissionsModel.js
- models/campaignModel.js
- models/connectionsModel.js
- models/skilledImpactRequestsModel.js
- models/socialModel.js
- models/updateModel.js
- models/usersModel.js
yes all of them
console.log is dead, long live winston
Also I removed the line length limit, happy to discuss as I know it's pretty controversial, but for my 2 cents: we abandoned punch cards a long time ago, there's no need for strict line length rules, we should absolutely keep line length reasonable in code to improve readability, but most offending lines are just string literals or comments which are harmless and just annoying to have to splice.
> Fix all lint errors

- app/api/campaigns/index.js
- app/api/comments/index.js
- app/api/index.js
- app/api/maps/index.js
- app/api/social/index.js
- app/api/updates/index.js
- app/database/models/campaignModel.js
- app/database/models/commentsModel.js
- app/database/models/connectionsModel.js
- app/database/models/mapModel.js
- app/database/models/updateModel.js
- app/database/models/usersModel.js
Moved some routes to `async`/`await` and used guard clauses, cleaned up some database operations (including the big "get all campaigns" one and the connections model), etc. but there's a lot of this API that should be redesigned.
> cleaned up some API routes and database models

- app/api/reports/helpers.js
- app/api/reports/index.js
- knexfile.js
Fix two breaking, but small issues  in reports endpoints
> Fix outdated code in reports endpoints

- app/database/seeds/001-users.js
- app/database/seeds/002-conservationists.js
- app/database/seeds/003-campaigns.js
- app/database/seeds/004-campaign_posts.js
- app/database/seeds/005-comments.js
- app/database/seeds/006-skills.js
- app/database/seeds/007-skilled_impact_requests.js
- app/database/seeds/008-project_goals.js
- app/database/seeds/009-application_submissions.js
- app/database/seeds/010-supporters.js
- app/database/seeds/011-bookmarks.js
Inserting database seeds with IDs causes primary key conflicts because the internal auto-incrementing sequence is still at 1, so this PR comments out the seeds' IDs.
> fixed seed IDs

- app/api/campaigns/index.js
- app/database/models/campaignModel.js
Fixes campaign creation and a FE bug related to `setBookmark`.
> misc fixes from separating campaigns and posts

- Procfile
This should've gone in #212, my bad.
> added Procfile for automated database migrations

- app/database/models/usersModel.js
This field wasn't in the array of fields in the users model, so we had no way of updating it.
> Modify accepting_help_requests on PUT /users/:id

- app/api/campaigns/index.js
- app/database/models/campaignModel.js
Restore this API as we need it to search campaigns by skill.
> Restore campaigns API and model

- app/database/models/campaignPostsModel.js
Pass skill-impact-reqeusts data into the live feed.
> access skill impact req on frontend

- app/database/models/campaignPostsModel.js
Add group by clause to feed API
> Add group by clause to feed API

- app/database/models/campaignPostsModel.js
> ID Group by
